### ISSUE TITLE
I tested it using python 2.7.17 on both client and server.

### ISSUE THREAD

**Issue by lchang1977** [LoSgu8/SecuritySDN#2]
I tested it using python 2.7.17 on both client and server.

_Originally posted by @LoSgu8 in https://github.com/LoSgu8/SecuritySDN/issues/1#issuecomment-1276408723_
      thank you for your reply,but we still don't run this project successfully.

Error msg of ryu controller as follows(no method for uploading the msg pictures):
module’ object has no attribute 'compare_digest' .

**Comment by lchang1977** [comment]
when we run the scritp 'python clientsec.py' on h1,there is the wrong msg which is as follows:
ImportError:No module named msgpack.
We want to install the msgpack under python2.7.17,but the msgpack is not supported the python2 after version1.0,so if you tested the code under python2.7.17, how was the msgpack installed?we are looking forward for your answer.
thank you again.

**Comment by giacomosguotti** [comment]
Actually I managed to install msgpack 1.0.3 on it through pip install msgpack. msgpack documentation can be found here https://msgpack.org/
![msgpack](https://user-images.githubusercontent.com/17884896/195810996-be0a9b2b-3ba3-40f7-882e-9322a4666d09.PNG)
